### ISSUE TITLE
Window is not defined (uncaughtException)

### ISSUE THREAD

**Issue by Rayane-Puzenat** [gor181/react-chartjs-2#55]
Hi,

I am working on a _**no-isomorphic**_ app and I got this error. It's coming form the package react-chartjs-2 itself.

Error Log : 

```
> myapp-front@1.0.0 start-dev /home/safran/Dev/Myapp/Admin
> npm run build && NODE_ENV=development nodemon src/index.js --exec babel-node --presets es2015,stage-2 --ext js


> myapp-front@1.0.0 build /home/safran/Dev/Myapp/Admin
> webpack -d --progress

Hash: b444b947f5ab90805425  
Version: webpack 1.13.3
Time: 5755ms
	Asset     	Size  		Chunks               Chunk Names
    app.bundle.js  	3.14 MB       	0  [emitted]  	         main
app.bundle.js.map  	3.47 MB       	0  [emitted]  	         main

   [0] multi main 64 bytes {0} [built]
    + 1237 hidden modules

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js --presets es2015,stage-2`

2016-11-06T02:39:23.046Z - error: uncaughtException: window is not defined date=Sat Nov 05 2016 22:39:23 GMT-0400 (EDT), pid=8993, uid=1000, gid=1000, cwd=/home/safran/Dev/Myapp/Admin, execPath=/home/safran/.nvm/versions/node/v6.0.0/bin/node, version=v6.0.0, argv=[node, /home/safran/Dev/Myapp/Admin/src/index.js, --presets, es2015,stage-2], rss=107520000, heapTotal=83120128, heapUsed=61719536, loadavg=[1.5400390625, 2.1279296875, 1.93115234375], uptime=7969, trace=[column=10, file=/home/safran/Dev/Myapp/Admin/node_modules/react-chartjs-2/node_modules/chart.js/src/core/core.helpers.js, function=null, line=676, method=null, native=false, column=3, file=/home/safran/Dev/Myapp/Admin/node_modules/react-chartjs-2/node_modules/chart.js/src/core/core.helpers.js, function=module.exports, line=684, method=exports, native=false, column=31, file=/home/safran/Dev/Myapp/Admin/node_modules/react-chartjs-2/node_modules/chart.js/src/chart.js, function=, line=6, method=null, native=false, column=32, file=module.js, function=Module._compile, line=541, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=550, method=_extensions..js, native=false, column=7, file=/home/safran/Dev/Myapp/Admin/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=152, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=456, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=415, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=407, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=466, method=require, native=false], stack=[ReferenceError: window is not defined,     at /home/safran/Dev/Myapp/Admin/node_modules/react-chartjs-2/node_modules/chart.js/src/core/core.helpers.js:676:10,     at module.exports (/home/safran/Dev/Myapp/Admin/node_modules/react-chartjs-2/node_modules/chart.js/src/core/core.helpers.js:684:3),     at Object.<anonymous> (/home/safran/Dev/Myapp/Admin/node_modules/react-chartjs-2/node_modules/chart.js/src/chart.js:6:31),     at Module._compile (module.js:541:32),     at Module._extensions..js (module.js:550:10),     at Object.require.extensions.(anonymous function) [as .js] (/home/safran/Dev/Myapp/Admin/node_modules/babel-register/lib/node.js:152:7),     at Module.load (module.js:456:32),     at tryModuleLoad (module.js:415:12),     at Function.Module._load (module.js:407:3),     at Module.require (module.js:466:17)]

[nodemon] clean exit - waiting for changes before restart
```

Thank you for your help.

**Comment by udisun** [comment]
+1

**Comment by selimovicz** [comment]
+1

**Comment by gor181** [comment]
Hello,

There is a potential solution on this at: https://github.com/reactjs/react-chartjs/issues/57
As there is no window while doing server rendering we cannot do much as a part of this lib.

Thanks all for reporting 👍
